### PR TITLE
🎨 Placeholder image to fulfill the empty space in my heart.

### PR DESCRIPTION
**Pull request by ImKyleJK**
Signed-off-by: ImKyleJK <me@imkylejk.me>

### CODE REVIEW

**Review by NotReeceHarris — COMMENTED** [review]
dunno about that image lol

**Comment by ImKyleJK** [comment]
Daym

**Comment by ImKyleJK** [comment]
Better than the original one i had, it is only temp

**Comment by NotReeceHarris** [comment]
also im changing the source to csharp

**Comment by ImKyleJK** [comment]
Okay. :))

**Comment by NotReeceHarris** [comment]
im currently changing the readme so send me the image in a bit

**Comment by ImKyleJK** [comment]
mk also ik this shouldnt be here but...
image
do they need read to all the private repos

**Pull request closed without merging**
